// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: fileformat/csvformat.proto

package fileformat

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TestRecordFormatDefault with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TestRecordFormatDefault) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestRecordFormatDefault with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestRecordFormatDefaultMultiError, or nil if none found.
func (m *TestRecordFormatDefault) ValidateAll() error {
	return m.validate(true)
}

func (m *TestRecordFormatDefault) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TestRecordId

	// no validation rules for Double_

	// no validation rules for Float_

	// no validation rules for Int32_

	// no validation rules for Int64_

	// no validation rules for Uint32_

	// no validation rules for Uint64_

	// no validation rules for Sint32_

	// no validation rules for Sint64_

	// no validation rules for Fixed32_

	// no validation rules for Fixed64_

	// no validation rules for Sfixed32_

	// no validation rules for Sfixed64_

	// no validation rules for Bool_

	// no validation rules for String_

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return TestRecordFormatDefaultMultiError(errors)
	}

	return nil
}

// TestRecordFormatDefaultMultiError is an error wrapping multiple validation
// errors returned by TestRecordFormatDefault.ValidateAll() if the designated
// constraints aren't met.
type TestRecordFormatDefaultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestRecordFormatDefaultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestRecordFormatDefaultMultiError) AllErrors() []error { return m }

// TestRecordFormatDefaultValidationError is the validation error returned by
// TestRecordFormatDefault.Validate if the designated constraints aren't met.
type TestRecordFormatDefaultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestRecordFormatDefaultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestRecordFormatDefaultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestRecordFormatDefaultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestRecordFormatDefaultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestRecordFormatDefaultValidationError) ErrorName() string {
	return "TestRecordFormatDefaultValidationError"
}

// Error satisfies the builtin error interface
func (e TestRecordFormatDefaultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestRecordFormatDefault.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestRecordFormatDefaultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestRecordFormatDefaultValidationError{}

// Validate checks the field values on TestRecordWithError with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TestRecordWithError) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TestRecordWithError with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TestRecordWithErrorMultiError, or nil if none found.
func (m *TestRecordWithError) ValidateAll() error {
	return m.validate(true)
}

func (m *TestRecordWithError) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBase()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TestRecordWithErrorValidationError{
					field:  "Base",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TestRecordWithErrorValidationError{
					field:  "Base",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBase()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TestRecordWithErrorValidationError{
				field:  "Base",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ErrorContent

	if len(errors) > 0 {
		return TestRecordWithErrorMultiError(errors)
	}

	return nil
}

// TestRecordWithErrorMultiError is an error wrapping multiple validation
// errors returned by TestRecordWithError.ValidateAll() if the designated
// constraints aren't met.
type TestRecordWithErrorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TestRecordWithErrorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TestRecordWithErrorMultiError) AllErrors() []error { return m }

// TestRecordWithErrorValidationError is the validation error returned by
// TestRecordWithError.Validate if the designated constraints aren't met.
type TestRecordWithErrorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TestRecordWithErrorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TestRecordWithErrorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TestRecordWithErrorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TestRecordWithErrorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TestRecordWithErrorValidationError) ErrorName() string {
	return "TestRecordWithErrorValidationError"
}

// Error satisfies the builtin error interface
func (e TestRecordWithErrorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTestRecordWithError.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TestRecordWithErrorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TestRecordWithErrorValidationError{}

// Validate checks the field values on DatetimeRecordFormatDefault with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DatetimeRecordFormatDefault) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DatetimeRecordFormatDefault with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DatetimeRecordFormatDefaultMultiError, or nil if none found.
func (m *DatetimeRecordFormatDefault) ValidateAll() error {
	return m.validate(true)
}

func (m *DatetimeRecordFormatDefault) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetDatetime1_()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime1_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime1_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDatetime1_()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DatetimeRecordFormatDefaultValidationError{
				field:  "Datetime1_",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDatetime3_()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime3_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime3_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDatetime3_()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DatetimeRecordFormatDefaultValidationError{
				field:  "Datetime3_",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDatetime5_()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime5_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime5_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDatetime5_()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DatetimeRecordFormatDefaultValidationError{
				field:  "Datetime5_",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDatetime7_()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime7_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime7_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDatetime7_()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DatetimeRecordFormatDefaultValidationError{
				field:  "Datetime7_",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDatetime9_()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime9_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DatetimeRecordFormatDefaultValidationError{
					field:  "Datetime9_",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDatetime9_()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DatetimeRecordFormatDefaultValidationError{
				field:  "Datetime9_",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return DatetimeRecordFormatDefaultMultiError(errors)
	}

	return nil
}

// DatetimeRecordFormatDefaultMultiError is an error wrapping multiple
// validation errors returned by DatetimeRecordFormatDefault.ValidateAll() if
// the designated constraints aren't met.
type DatetimeRecordFormatDefaultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DatetimeRecordFormatDefaultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DatetimeRecordFormatDefaultMultiError) AllErrors() []error { return m }

// DatetimeRecordFormatDefaultValidationError is the validation error returned
// by DatetimeRecordFormatDefault.Validate if the designated constraints
// aren't met.
type DatetimeRecordFormatDefaultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DatetimeRecordFormatDefaultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DatetimeRecordFormatDefaultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DatetimeRecordFormatDefaultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DatetimeRecordFormatDefaultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DatetimeRecordFormatDefaultValidationError) ErrorName() string {
	return "DatetimeRecordFormatDefaultValidationError"
}

// Error satisfies the builtin error interface
func (e DatetimeRecordFormatDefaultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDatetimeRecordFormatDefault.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DatetimeRecordFormatDefaultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DatetimeRecordFormatDefaultValidationError{}

// Validate checks the field values on DatetimeRecordWithError with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DatetimeRecordWithError) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DatetimeRecordWithError with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DatetimeRecordWithErrorMultiError, or nil if none found.
func (m *DatetimeRecordWithError) ValidateAll() error {
	return m.validate(true)
}

func (m *DatetimeRecordWithError) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBase()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, DatetimeRecordWithErrorValidationError{
					field:  "Base",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, DatetimeRecordWithErrorValidationError{
					field:  "Base",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBase()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return DatetimeRecordWithErrorValidationError{
				field:  "Base",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ErrorContent

	if len(errors) > 0 {
		return DatetimeRecordWithErrorMultiError(errors)
	}

	return nil
}

// DatetimeRecordWithErrorMultiError is an error wrapping multiple validation
// errors returned by DatetimeRecordWithError.ValidateAll() if the designated
// constraints aren't met.
type DatetimeRecordWithErrorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DatetimeRecordWithErrorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DatetimeRecordWithErrorMultiError) AllErrors() []error { return m }

// DatetimeRecordWithErrorValidationError is the validation error returned by
// DatetimeRecordWithError.Validate if the designated constraints aren't met.
type DatetimeRecordWithErrorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DatetimeRecordWithErrorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DatetimeRecordWithErrorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DatetimeRecordWithErrorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DatetimeRecordWithErrorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DatetimeRecordWithErrorValidationError) ErrorName() string {
	return "DatetimeRecordWithErrorValidationError"
}

// Error satisfies the builtin error interface
func (e DatetimeRecordWithErrorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDatetimeRecordWithError.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DatetimeRecordWithErrorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DatetimeRecordWithErrorValidationError{}
